apiVersion: 1

groups:
  - orgId: 1
    name: rds-connection-alerts
    folder: RDS Monitoring
    interval: 60s
    rules:
      - uid: high_rds_conn_count
        title: High RDS Connection Count 
        condition: A
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: aws_rds_database_connections_average > 100
              datasource:
                type: prometheus
                uid: prometheus
              format: time_series
              interval: ""
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
              instant: false
              step: 60
              type: timeSeriesQuery
            relativeTimeRange:
              from: 300
              to: 0
        noDataState: Alerting
        execErrState: Alerting
        for: 60s
        annotations:
          summary: "High number of RDS connections"
          description: "RDS instance has more than 100 active connections"
        labels:
          severity: warning
          team: sre
