global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cloudwatch_rds'
    static_configs:
      - targets: ['cloudwatchexporter:9106']